dataset_path: "../datasets/MEDIC/data/multimodal-deep-learning-disaster-response-mouzannar/multimodal"

learning_rate: 0.00005
split_ratio: 0.9
batch_size: 16

start_epoch: 11
epoch: 50
checkpoint_dir: "chkpt/resnest"
checkpoint_epoch: 1

